/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:91e0c286-7113-42af-bcee-384d2a450f69",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lFWOicj8T",
    "aws_user_pools_web_client_id": "7d5up9vbma1luj5c9gc3c5ku0m",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cao5rg7thbdv7cn3ehngx5cel4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-utjv4wjca5bb5fyuy7zibfgsmq",
    "aws_cloud_logic_custom": [
        {
            "name": "probablefutures",
            "endpoint": "https://z2nfgfuf2e.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
